parameters:
#    chipin_core.example.class: Chipin\CoreBundle\Example

services:
#    chipin_core.example:
#        class: %chipin_core.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
