chipin_admin:
    resource: "@ChipinAdminBundle/Resources/config/routing.yml"
    prefix:   /

chipin_db:
    resource: "@ChipinDBBundle/Resources/config/routing.yml"
    prefix:   /

chipin_core:
    resource: "@ChipinCoreBundle/Resources/config/routing.yml"
    prefix:   /

acme_hello:
    resource: "@AcmeHelloBundle/Resources/config/routing.yml"
    prefix:   /

