parameters:
#    chipin_db.example.class: Chipin\DBBundle\Example

services:
#    chipin_db.example:
#        class: %chipin_db.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
